post:
  operationId: importTasks
  tags: [tasks]
  summary: Bulk import tasks
  parameters:
    - $ref: '../../parameters/RoomIdPath.yaml'
    - $ref: '../../parameters/AdminCodeHeader.yaml'
  requestBody:
    required: true
    content:
      application/json:
        schema:
          $ref: '../../schemas/request/ImportTasksRequest.yaml'
  responses:
    '201':
      description: Tasks imported
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '../../schemas/response/TaskResponse.yaml'
